#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WarGame.Resource", IsApplication=true)]

namespace WarGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Clubs10 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Clubs2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Clubs3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Clubs4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Clubs5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Clubs6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Clubs7 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Clubs8 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Clubs9 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ClubsAce = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ClubsJ = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ClubsK = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ClubsQ = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Diamonds10 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Diamonds2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Diamonds3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Diamonds4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Diamonds5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Diamonds6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Diamonds7 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Diamonds8 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Diamonds9 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int DiamondsAce = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int DiamondsJ = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int DiamondsK = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int DiamondsQ = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Hearts10 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Hearts2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Hearts3 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Hearts4 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Hearts5 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Hearts6 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Hearts7 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Hearts8 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Hearts9 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int HeartsAce = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int HeartsJ = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int HeartsK = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int HeartsQ = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Joker = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Spades10 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Spades2 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Spades3 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Spades4 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Spades5 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Spades6 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Spades7 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Spades8 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Spades9 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int SpadesAce = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int SpadesJ = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int SpadesK = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int SpadesQ = 2130837557;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int card1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int card2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int currentScore = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int dealHand = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int player1Score = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int player2Score = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int previousGamesList = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int roundFeedback = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int startGame = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GamePlay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
